### ISSUE TITLE
No effect on CLion 2017.1.2

### ISSUE THREAD

**Issue by qywx** [ArtsiomCh/CMake#1]
I tried to install the plugin manually and through CLion's "install from local file".

**Comment by qywx** [comment]
![image](https://user-images.githubusercontent.com/13828976/32138047-ddeb90a8-bc34-11e7-9968-f528aecc46b9.png)

Where to get it?

**Comment by ArtsiomCh** [comment]
CLion has it own CMake built-in support which can't be replaced. 
As far as I understand CMake in CLion is major building system (same like Gradle in Android Studio), so no side plugin can overload it. 

Presently, plugin been tested and works with **IntelliJ IDEA CE** and  **Android Studio** only. Other IntelliJ Idea IDEs haven't been tested (PyCharm, WebStorm, etc.) but potentially might be supported. 

You can try to allow installing the plugin to any  IntelliJ Idea IDEs by replacing `  <depends>com.intellij.modules.java</depends>` with `<depends>com.intellij.modules.lang</depends>` at `resources/META-INF/plugin.xml` (See [Plugin Compatibility with IntelliJ Platform Products](https://www.jetbrains.org/intellij/sdk/docs/basics/getting_started/plugin_compatibility.html) for details.). And then rebuild project following Build Instruction from README.md. 
But you'll have to deal with any possible conflicts by yourself (like the conflict with built-in CMake support in CLion).

**Comment by qywx** [comment]
@ArtsiomCh, thank you.
I will try some time later.

**Comment by ArtsiomCh** [comment]
@sledgeh Try new 0.1.0 version. Extended highlighting added on top of CLion's built-in CMake plugin.
