### ISSUE TITLE
Plugin breakes highlighting correspondent angle and curve braces.

### ISSUE THREAD

**Issue by pavelliavonau** [ArtsiomCh/CMake#10]
It's important when editing complex generator expressions.
Example string is next:
`set_config_specific_property("OUTPUT_DIRECTORY" "${CMAKE_CURRENT_SOURCE_DIR}$<$<NOT:$<STREQUAL:${CMAKE_VS_PLATFORM_NAME},Win32>>:/${CMAKE_VS_PLATFORM_NAME}>/${PROPS_CONFIG}")`

Before install:
![image](https://user-images.githubusercontent.com/1422396/69955470-c4944c00-150e-11ea-976e-75f676ed3261.png)

After install:
![image](https://user-images.githubusercontent.com/1422396/69955650-35d3ff00-150f-11ea-99a5-4af7174175e0.png)

To reproduce: just place cursor at left angle brace, right brace must be highlighted.
Note: auto highlighting of () braces works fine.

ALSO: auto highlighing of curve braces {} also is broken.

I'm using CMake simple highlighter version 191.2
Pycharm 2018.2.3

**Comment by ArtsiomCh** [comment]
Looks like this is kind of "feature-bug". All JB IDEs do those brace matching for the plain text (which any CMake file is in PyCharm by default). That requires lexer recognition for those braces as separate tokens or else do some more complicated magic...
Not sure I'll implement that in my lexer. It looks too much work for so little feature.
Anyway, Thank you for pointing out this thing! At least I explore brace matching mechanisms in more detail, which might help me to do brace matching more sophisticated way in the future. :)

PS: Just curious, why are you using outdated Pycharm 2018.2.3? If you move to at least 2019.2 you'll get much more new functionality implemented in my plugin...
