### ISSUE TITLE
New command `target_precompile_headers` is not recognized

### ISSUE THREAD

**Issue by liurui39660** [ArtsiomCh/CMake#12]
In CMake 3.16, there are a new command `target_precompile_headers` which adds supports for precompiled headers, [doc page](https://cmake.org/cmake/help/v3.16/command/target_precompile_headers.html). But currently, this command is not recognized as a keyword by the plugin. Please consider adding it.

**Comment by ArtsiomCh** [comment]
Thanks for pointing that out. I used the older version of CMake to get the list of commands. Will update it in the next release.

**Comment by ArtsiomCh** [comment]
Fixed at 193.3.1:
Update to Cmake 3.16.2 for commands, modules, policies, properties, variables and corresponding Quick Documentation.
