### ISSUE TITLE
"OUTPUT" of ADD_CUSTOM_COMMAND is not highlighted

### ISSUE THREAD

**Issue by liurui39660** [ArtsiomCh/CMake#14]
## What happened

`OUTPUT` of `ADD_CUSTOM_COMMAND` is not highlighted as a CMake property.

## How to reproduce

- Open a `CMakeLists.txt` file.
- Copy & paste the following code snippet
```cmake
ADD_CUSTOM_COMMAND(
	OUTPUT ${KERNEL_EMBEDDED}
	COMMAND bin2c -c -p 0 -n codeEmbeddedPTX ${KERNEL_PTX} > ${KERNEL_EMBEDDED}
	DEPENDS ${KERNEL_PTX}
)
```

## Expected result

`OUTPUT` is highlighted as a CMake property.

## Actual result

It shows the color of normal text.

## System info

CLion 2019.3.4
Build #CL-193.6494.38, built on February 11, 2020
Runtime version: 11.0.5+10-b520.38 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
CMake simple highlighter: 193.3.2
CMake Plus: 193.3.1

**Comment by ArtsiomCh** [comment]
For now, only CMake properties described at https://cmake.org/cmake/help/v3.16/manual/cmake-properties.7.html are correctly highlighted.
All command-specific properties (like OUTPUT for ADD_CUSTOM_COMMAND) are not recognized.
Also, COMMANDS and DEPENDS are recognized here occasionally, just cause similar global properties/operators exist.

PS Planning to implement more semantic checks in the future. It just needs to input all that rules manually and it gonna take a lot of time probably...

**Comment by ArtsiomCh** [comment]
Done in 223.1.0 (and up) of CMake Plus plugin
