### ISSUE TITLE
please make a release for the new clion EAP 202.0

### ISSUE THREAD

**Issue by csitarichie** [ArtsiomCh/CMake#17]
ones you update to latest CLion EAP the plugin is not compatible anymore 

			Plugin "CMake simple highlighter" is incompatible (until build 202.0 < CL-202.5428.21).
			Plugin "CMake Plus" is incompatible (until build 202.0 < CL-202.5428.21).

Is there a way to fix this? I really miss it now :).

**Comment by ArtsiomCh** [comment]
Planning to do that ASAP. There's some issues with new API in 202. Hope will be able to fix it over this weekend. Sorry for inconvenience.

**Comment by ArtsiomCh** [comment]
Fixed at 202.0.1
