### ISSUE TITLE
"FetchContent_XXX" is not highlighted

### ISSUE THREAD

**Issue by DevDengChao** [ArtsiomCh/CMake#19]
![QQ截图20201202155538](https://user-images.githubusercontent.com/16363180/100844594-07d52200-34b7-11eb-89b0-ab1c569cac32.png)

Ref:
https://cmake.org/cmake/help/latest/module/FetchContent.html#commands

Environment:
CLion 2020.2.5
Build #CL-202.8194.17, built on November 26, 2020
Non-Bundled Plugins: artsiomch.cmake 203.0.1, artsiomch.cmake.plus 203.0.1

**Comment by ArtsiomCh** [comment]
Hi, thanks for reporting.
For now plugin knows only about [**modules**](https://cmake.org/cmake/help/latest/manual/cmake-modules.7.html) (see `FetchContent` above) but not about **module's internal command**s (`FetchContent_Declare`, etc...).
It might be implemented in the future, but no commitment.
