### ISSUE TITLE
CMake simple highlighter is incompatible with PyCharm EAP 2020.1

### ISSUE THREAD

**Issue by knzivid** [ArtsiomCh/CMake#23]
The error text is `Incompatible: requires IDE build 204 or older`

**Comment by ArtsiomCh** [comment]
Hi, just checked with 
PyCharm 2020.1.1 (Community Edition) Build #PC-201.7223.92
Latest CMake simple highlighter 203.0.2 was installed and works as expected.
Could you please provide more details?

**Comment by knzivid** [comment]
I used https://aur.archlinux.org/packages/pycharm-community-eap at version 2021.1.211.5538.22

**Comment by ArtsiomCh** [comment]
So you mean 2021.1 not 2020.1, correct?
If so, 2021 is in eap and not supported yet. Will release new version after it's turns into Beta at least.

**Comment by knzivid** [comment]
Thanks

**Comment by knzivid** [comment]
My bad, I now notice the title of this issue was wrong :(
