### ISSUE TITLE
CMake-simple-highlighter-211.0.1.jar contains invalid plugin descriptor

### ISSUE THREAD

**Issue by hgkjshegfskef** [ArtsiomCh/CMake#28]
Clion 2021.2.1 says in the event log:

> File '~/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/212.5080.54.plugins/CMake-simple-highlighter-211.0.1.jar' contains invalid plugin descriptor

Although the plugin seems to work (it highlights CMake just fine).

**Comment by ArtsiomCh** [comment]
Thanks for reporting! Seems not affecting plugin functionality. Will fix plugin descriptor eventually.
