### ISSUE TITLE
Infinite loop when opening string quotation marks

### ISSUE THREAD

**Issue by TeddybearCrisis** [ArtsiomCh/CMake#3]
### Summary
Using the newest CLion version I want to set quotation marks before and after the value part of the following statement:
`set(VARNAME valuePart)` 

### Experienced
When putting the opening quotation mark CLion becomes unresponsive and CPU load rises intensely. I need to kill the clion process and restart it. I waited for a few minutes before doing so. Though your highlighter might recover successfully after some time I still think it's undesireable behaviour.

### Expected Results
I want to edit the cmake script without clion becoming unresponsive or causing massive CPU load.

### Steps to reproduce
It occured after updating CLion to the newest version (see below). Unfortunately I'm unable to provide a reliable minimal example. It occured multiple times when setting an opening quotation mark at different locations in the script. The sample command above on its own doesn't cause the effect. I have a larger cmake script I don't want to expose here following the above statement. To me it looks like your highlighter wants to parse the entire script as string statement and gets stuck in complexity or some special case. I deactivated your plugin and didn't experience it since. So I assume your plugin is the culprit (unless weird changes within CLion itself are the cause). In case I find a reliable minimal example I'll report back.

### Environment
CLion 2018.2.5
Build #CL-182.4892.24, built on October 16, 2018
Licensed to CLion Evaluator
Expiration date: November 14, 2018
JRE: 1.8.0_152-release-1248-b19 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by ArtsiomCh** [comment]
Thanks for letting me know. Will check it withing nearest days.

**Comment by TeddybearCrisis** [comment]
Thanks for the plugin - no hurry.

**Comment by ArtsiomCh** [comment]
@TeddybearCrisis Unfortunately, I can't reproduce your issue. 
I tried with my ["smoke test" file](CMake/test_files/CMakeLists1.cmake) and few quite complicated [cmake files](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/cmake) from TensorFlow project.
After inserting open quotation mark, plunging indeed trying to parse the rest of the file as a string and CPU loads increase. But that usually ends within 2-10 seconds. Adding/deleting another quotation mark cause reparsing process which also usually ends within 2-10 seconds (depends on the file length).
Please, try to find and send me a code to make your issue reproducible.
