### ISSUE TITLE
CMakePlus doesn't display documentation since update to CLion 2021.3

### ISSUE THREAD

**Issue by j-silver** [ArtsiomCh/CMake#31]
When hovering on a cmake command it used to show documentation about the command, now I only see a tooltip saying "Fetching documentation..." but it doesn't download (I suppose) the docs from Internet. Clicking on the menu and choosing "Open in a documentation tool window" gives the same message

![Screenshot from 2021-12-03 17-57-41](https://user-images.githubusercontent.com/9558931/144650333-3e77ccd6-342f-4cfb-bb1e-6fd1ff0dc6af.png)

**Comment by ArtsiomCh** [comment]
Thanks! Could you please check you are on latest **213.1.2** plugin version (Settings-Plugins-Installed)
Also check please in Help-Register that your Cmake Plus license is correctly recognized and not expire.

**Comment by j-silver** [comment]
Hi, yes, it's the latest version and the license is valid until the 20th of February 2022.

**Comment by ArtsiomCh** [comment]
Do you see balloon notification with message `CMake Plus plugin License not found. Plugin functionality will be disabled.` when Clion starts?
PS also try to uninstall, restart Clion and then install again **both** `Cmake simple highlighter` and `Cmake plus` plugins.

**Comment by ArtsiomCh** [comment]
Also all docs are stored locally, so no internet connection is needed for that functionality.

**Comment by ArtsiomCh** [comment]
Could you see docs for any other items, not Cmake one but for C++/C code for example? 
It looks like receiving docs for element mechanism inside your Clion is broken for some reason, so I'm curious if any other docs are displayed in your case...

**Comment by j-silver** [comment]
I've uninstalled both plugins, restarted CLion, re-installed and restarted again. But no luck.

The C++ documentation for the code is displayed as usual.

**Comment by ArtsiomCh** [comment]
Found some changes made by Jetbrains in license check process if licensed via ticket obtained from JetBrains Floating License Server. Please let me know if that's your case?
Also try please [213.1.3](https://drive.google.com/file/d/1Uh63Sf0U_F9hA0_DCceE8WpfNxId8DKc/view?usp=sharing) with fix for such cases by manually installing it from the disk:
![image](https://user-images.githubusercontent.com/14268320/144721065-66b22fbd-7c0f-4b90-93b7-ec3714f0c8b2.png)

**Comment by j-silver** [comment]
It still doesn't work.

Does the plugin use the documentation from the cmake bundled with CLion? Because I also have cmake installed from my distribution, Fedora (although it has never been a problem)

**Comment by ArtsiomCh** [comment]
@j-silver And you still see balloon notification with message `CMake Plus plugin License not found. Plugin functionality will be disabled.` when Clion starts even with 213.1.3?

**Comment by j-silver** [comment]
@ArtsiomCh I haven't seen any balloon notification at startup, not before, not now. The plugin is shown as enabled and the license recognised as still valid.

**Comment by ArtsiomCh** [comment]
@j-silver good to know, then I've been soling wrong problem :) Unfortunately, I can't preproduce the problem anyhow, so I can only guessing...
Ok, could you please try to install next version with **excessive logging** for doc fetching process **for cmake commands**: [213.1.3-docs-log1](https://drive.google.com/file/d/152KGOWSdLERljdhXt-PZcfrpPEzWMdA9/view?usp=sharing)

- Then try to get docs for few cmake commands (to get those "Fetching documentation...") **and** also for few other cmake items please (like predefined variables or operators, etc.)
- Then close IDE.
- Then [find idea.log file](https://intellij-support.jetbrains.com/hc/en-us/articles/207241085-Locating-IDE-log-files) and send it to me **privately** (as It might contain some sensitive information like your PC name) to achapialiou@gmail.com.

**Comment by j-silver** [comment]
Done. I think that the plugin **CMake Docs** is causing the issue. So I've uninstalled it and then reinstalled the current version of CMake Plus (213.1.2). Now the documentation is working properly.

**Comment by ArtsiomCh** [comment]
Yep, you're totally right. CMake Docs plugin is using the same mechanism to provide docs. And as far as it's unmaintained anymore - it's fail to obtain docs and broke the whole queue of all other docProviders. So mine was not even called out...
Would try to contact the author to ask him to update the plugin or remove it from marketplace.
