### ISSUE TITLE
Description states that JetBrains Marketplace Licensing Support should be installed automatically, but this only happens in some JetBrains IDEs, not all

### ISSUE THREAD

**Issue by CarlMitchellKT** [ArtsiomCh/CMake#32]
Description states that JetBrains Marketplace Licensing Support should be installed automatically.

This only happens in the IDEs JetBrains Marketplace Licensing Support is officially compatible with: IntelliJ IDEA Community, Android Studio, IntelliJ IDEA Educational, MPS, PyCharm Community, and PyCharm Educational.

It doesn't happen in other IDEs that CMake Plus supports, such as CLion, AFAICT because plugins that don't list compatibility don't get automatically installed.

It's easy to manually install (though updates aren't automatic), but the description should probably note this.

**Comment by ArtsiomCh** [comment]
Thanks for pointing that out.
afaik JetBrains Marketplace Licensing Support needed for free IDE only. It's automatically bundled (build-in) into commercial IDE. So no extra action needed in case of CLion.
Will update description.

**Comment by ArtsiomCh** [comment]
Actually it looks like JetBrains Marketplace Licensing Support is bundled now with free IDE as well...

**Comment by ArtsiomCh** [comment]
Description fixed at 213.1.4
