### ISSUE TITLE
Add Syntax for FetchContent

### ISSUE THREAD

**Issue by ChainofChaos** [ArtsiomCh/CMake#34]
Currently, the CMake plugin and CLion don't recognize FetchContent and don't have an autocomplete or syntax highlighting. Can you add it, please? thanks
![image](https://user-images.githubusercontent.com/17515882/180643087-c760cb50-ed03-404e-b782-fd0bd6fe5fc1.png)

**Comment by ArtsiomCh** [comment]
FetchContent_XXX commands are from FetchContent module. All such "extra" commands are not supported (highlighting, quickdocs, etc) in my plugins yet. 
Planning to do such support (at least partially) in the nearest month.
Anyway, Thank you for pointing the issue and making me more confident I'm on right track of implementing that!

**Comment by ArtsiomCh** [comment]
related to #14

**Comment by ArtsiomCh** [comment]
Done at [222.4.0](https://plugins.jetbrains.com/plugin/12869-cmake-plus/versions/stable/228537) version of Cmake Plus
