### ISSUE TITLE
Can not comment code with shortcut.

### ISSUE THREAD

**Issue by Matt-V50** [ArtsiomCh/CMake#39]
# Version 

- plugin: 222.7.0-NCL
- pycharm: PyCharm 2021.3.3 (Professional Edition)

# Problem

![image](https://user-images.githubusercontent.com/16064851/201522042-82a3186b-a10d-47c1-a9c4-ff685bbb551d.png)

It might just not comment on the code line. Here the button in `code` tab is gray.

# Reference

[plugin needs a implement - intellij-support](https://intellij-support.jetbrains.com/hc/en-us/community/posts/115000118344/comments/360000105330)

**Comment by ArtsiomCh** [comment]
Hmm... Just checked with PyCharm 2022.2.3 (Professional Edition). Turning line into comment with shortcut (Ctrl + /) work as expected. Also available (not grayed) through menu:
![image](https://user-images.githubusercontent.com/14268320/201522624-769bd7ac-2ae1-45c7-8440-4e0dc73e706c.png)

Please check next things:
1. You have both **CMake Plus** and **CMake simple highlighter** plugins installed.
2. For shortcut usage you are in English keyboard layout.

**Comment by Matt-V50** [comment]
Yes, you are right, I miss `CMake Plus`, but `CMake plus` needs a subscription after 30 days of free trials. Maybe I should use `Clion` instead.

**Comment by ArtsiomCh** [comment]
If you need just read/write simple cmake build scripts - then **CMake simple highlighter** could be enough.
If you want  more sophisticated support and work with complicated/large and cross-connected cmake scripts - then **CMake Plus** could definitely helps.
PS Also either of the plugins has extra features even on top of what Clion provide.
PPS Anyway, Thank you for trying my plugins! And if you experience any problem with either of them, I would be happy to help/answer your issue.
