### ISSUE TITLE
Invalid on android studio 3.2.1

### ISSUE THREAD

**Issue by moyergo** [ArtsiomCh/CMake#4]
Invalid on android studio 3.2.1. I installed it from Browse Repositories and also restarted my AS.

**Comment by ArtsiomCh** [comment]
Just checked with AS 3.2.1 everything works as expected. Could you describe in more details, please, what is invalid in your case?

PS make sure you open project with C++ support and your CMakeLists.txt file is connected (through Gradle) to your project. Just opening CMakeLists.txt (or "*.cmake" file) in AS would not make it recognizable by AS as cmake file, and my plugin will not see it as well.

**Comment by moyergo** [comment]
I just created a default project with AS (File - New - New Project - check Include C++ support, then next until finish), it runs on the phone is no problem.

The computer I work for at the company is also AS 3.2.1, but everything is fine. Going back to my own computer is not effective, which makes me very puzzled. The system is all windows 10 .

**Comment by ArtsiomCh** [comment]
My plugin works on top of builtin CMake plugin and provides just additional syntax highlight in AS. 
So, if you have a problem with builtin CMake plugin functionality you need to submit the issue to AS support team.

**Comment by moyergo** [comment]
thank you
