### ISSUE TITLE
string(REGEX) highlighting for character classes containing escaped characters

### ISSUE THREAD

**Issue by jschwe** [ArtsiomCh/CMake#47]
When writing a CMake regex such as 
```cmake
string(REGEX MATCH
        "^([a-z0-9_\.]+)-somethingelse$"
        outvar
        "${input}"
        )
```

The highlighting stops at `\` character, with the following message:
```
Unclosed character class
<literal>, VARIABLE_REFERENCE_START or literal expected, got '\'
```

My suggestion would to just allow `\` in the character class, without checking if it is a valid escape or not, since:

>  Escaping a non-special character is unnecessary but allowed, e.g. \a matches a. (CMake documentation)

**Comment by ArtsiomCh** [comment]
Thanks for reporting!
It's CLion parser bug (try with CMake Plus plugin disabled).
Also seems to be related to [CPP-30556](https://youtrack.jetbrains.com/issue/CPP-30556/cmake-parsing-is-broken-on-symbol-inside-quoted-argument) which is marked as solved in upcoming CLion 2023.2 EAP
