### ISSUE TITLE
Incompatible: requires IDE build 234

### ISSUE THREAD

**Issue by zhubeilife** [ArtsiomCh/CMake#60]
Hi,
  I am using clion nova version which is need build newer than 234.
  Do we consider a new version for this.

Thanks!

**Comment by ArtsiomCh** [comment]
Hi, current supported latest IDE version is 2023.3 (latest release).
2024.1 is still in EAP stage and support for it is coming soon.

**Comment by zhubeilife** [comment]
@ArtsiomCh 
> 2024.1 is still in EAP stage and support for it is coming soon.

Thanks! Because I'm using the free EAP version 😂.

**Comment by ArtsiomCh** [comment]
2024.1 IDE version support provided in 241.0.1 plugin version
