### ISSUE TITLE
Problem with Syntax Highlight of CMake Variable Reference 

### ISSUE THREAD

**Issue by ghost** [ArtsiomCh/CMake#62]
There is a visual conflict problem with CMake variables in themes with high contrast (presumably the JetBrains Dark Mode theme is not affected).

Disabling the CMake Plus / CMake simple highlighter plugin makes the problem disappear.

Here is an example of what I get with a CMake variable using the "One Dark Vivid" theme:
![CleanShot 2024-03-14 at 13 25 29@2x](https://github.com/ArtsiomCh/CMake/assets/124262680/ebe8de17-d767-4895-a33b-371e8d4895d5)
![CleanShot 2024-03-14 at 13 28 00@2x](https://github.com/ArtsiomCh/CMake/assets/124262680/d6c5dd2b-9eb0-4545-99e6-3f2e1bc245ce)

I'm not sure if this is a plugin issue, but if anyone has encountered the same problem and found a solution, I would be grateful!

**Comment by ghost** [comment]
Note: <del>I don't seem to have the problem on Windows. I found the problem on my MacBook Pro (macOS Sonoma).</del>

EDIT: 
I have the same problem on Windows.
I had the CMake Plus plugin deactivated and hadn't noticed this. Probably a bad synchronization of my IDE settings...
So sorry for the wrong indication: the problem occurs on macOS and Windows.

**Comment by ArtsiomCh** [comment]
Thanks for reporting!
Reproduced with One Dark Theme. 
Will try to produce fix soon.
For now use next workaround: set the same color (font and it attributes could be different) for "CMake variable reference" and "Local variable reference" in 

> Settings > Editor > Color Scheme > CMake additional syntax

![image](https://github.com/ArtsiomCh/CMake/assets/14268320/0df8af98-cb3d-4d16-a5c0-f57dcd869adb)

**Comment by ArtsiomCh** [comment]
Fixed in upcoming 241.1.1 version
Thanks again for reporting!
